site_name: Despliegue de Software
repo_url: https://github.com/ralvarezdev/uru-software-deployment/
repo_name: Despliegue de Software
edit_uri: edit/main/docs/
site_description: Documentación para la materia de Despliegue de Software de 
  la carrera de Ingeniería en Computación de la Universidad Rafael Urdaneta (URU).
site_author: Victoria Acosta, Ramón Álvarez, Idiar Chacín, Carlos Fernández, Angelina Pineda, Valeria Salcedo
use_directory_urls: false
theme:
  name: material
  logo: assets/images/logo/uru-var2.png
  favicon: assets/images/favicon/favicon.ico
  language: es
  features:
    - header.autohide
    - navigation.footer
  font:
    code: Fira Code
    text: Fira Sans
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon:  material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Inicio: index.md
  - Conceptos Básicos:
      - Almacenamiento:
          - RAID: concepts/storage/raid.md
      - Virtualización:
          - Contenedores:
              - Docker: concepts/virtualization/containers/docker.md
          - Máquinas virtuales: concepts/virtualization/virtual-machines.md
          - Servidores virtuales: concepts/virtualization/virtual-servers.md
      - Empaquetadores:
          - Vite: concepts/bundlers/vite.md
      - Sistemas de Gestión:
          - PM2: concepts/management-systems/pm2.md
          - CMS: concepts/management-systems/cms.md
      - Redes:
          - Dominio: concepts/network/domain.md
          - IP Pública: concepts/network/public-ip.md
          - Port Forwarding: concepts/network/port-forwarding.md
          - Protocolos:
              - Seguridad:
                  - SSL/TLS: concepts/network/protocols/security/ssl-tls.md
          - Seguridad:
              - Firewall:
                  - UFW: concepts/network/security/firewall/ufw.md
          - Hosting:
              - Apache: concepts/network/hosting/apache.md
              - Nginx: concepts/network/hosting/nginx.md
              - Virtual Host: concepts/network/hosting/virtual-host.md

  - Manual de Sistema:
      - Introducción: manual/index.md
      - Descripción del Sistema: manual/system-description.md
      - Requisitos del Sistema: manual/system-requirements.md
      - Instalación: manual/installation.md 
      - Configuración del entorno:
          - Configuración de red: manual/configuration/network/domain.md
          - Configuración del Nginx: manual/configuration/nginx.md
          - Configuración del UFW: manual/configuration/security/ufw.md
          - Configuración del HTTPS: manual/configuration/security/https.md
      - Solución de Problemas:
          - Errores Comunes: manual/common-errors.md
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ralvarezdev/uru-software-deployment
      name: GitHub
    - icon: fontawesome/solid/paper-plane
      link: mailto:<inquiries@ralvarez.dev>
      name: Enviar un correo
copyright:
  Copyright &copy; 2025 Victoria Acosta, Ramón Álvarez, Idiar Chacín, Carlos 
  Fernández, Angelina Pineda, Valeria Salcedo. All rights reserved.
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - nl2br
plugins:
  - search
  - callouts