version: '3.8'
services:
  auth_db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_AUTH_USER}
      - POSTGRES_PASSWORD=${POSTGRES_AUTH_PASSWORD}
      - POSTGRES_DB=${POSTGRES_AUTH_DB}
    ports:
      - "5433:5432"

  joke_db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_JOKE_USER}
      - POSTGRES_PASSWORD=${POSTGRES_JOKE_PASSWORD}
      - POSTGRES_DB=${POSTGRES_JOKE_DB}
    ports:
      - "5434:5432"