version: '3.8'
services:
  auth_db:
    build:
      context: ./auth_db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_AUTH_USER}
      - POSTGRES_PASSWORD=${POSTGRES_AUTH_PASSWORD}
      - POSTGRES_DB=${POSTGRES_AUTH_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./init/auth_db:/docker-entrypoint-initdb.d/
    restart: always

  joke_db:
    build:
      context: ./joke_db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_JOKE_USER}
      - POSTGRES_PASSWORD=${POSTGRES_JOKE_PASSWORD}
      - POSTGRES_DB=${POSTGRES_JOKE_DB}
    ports:
      - "5434:5432"
    volumes:
      - ./init/joke_db:/docker-entrypoint-initdb.d/
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "52318:80"
    restart: always